/******************************************************************************
*
* Copyright (C) 2009 - 2014 Xilinx, Inc.  All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* Use of the Software is limited solely to applications:
* (a) running on a Xilinx device, or
* (b) that interact with a Xilinx device through a bus or interconnect.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* XILINX  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
* OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*
* Except as contained in this notice, the name of the Xilinx shall not be used
* in advertising or otherwise to promote the sale, use or other dealings in
* this Software without prior written authorization from Xilinx.
*
******************************************************************************/

/* AUTOGENERATED COMMENTS
 *
 *
 * This application configures UART 16550 to baud rate 9600.
 * PS7 UART (Zynq) is not initialized by this application, since
 * bootrom/bsp configures it to baud rate 115200
 *
 * ------------------------------------------------
 * | UART TYPE   BAUD RATE                        |
 * ------------------------------------------------
 *   uartns550   9600
 *   uartlite    Configurable only in HW design
 *   ps7_uart    115200 (configured by bootrom/bsp)
 */



/*** Libraries ***/
#include "xparameters.h"	// System related parameters (produced by Vitis based on the provided XSA or HDF)
#include "sleep.h"			// Time based functions
#include "xil_printf.h"
#include <stdio.h>
#include <math.h>
#include <xil_exception.h>
#include "xintc.h"


#define AXI_IP_TEST_BUILD_DATE (XPAR_PICOZED_T_IP_0_BASEADDR+8)
#define AXI_IP_TEST_LATENCY_MEASURE (XPAR_PICOZED_T_IP_0_BASEADDR + 0x118)
#define AXI_IP_TEST_IRQ (0x43C00104)
#define ENABLE_PRINT 1

uint32_t* bramPtr_countIdx = (uint32_t*)(XPAR_MICROBLAZE_BRAM_CTRL_S_AXI_BASEADDR + 12); // 4 byte offset

uint32_t* LatencyControl = (uint32_t*)(AXI_IP_TEST_LATENCY_MEASURE);

float globalValue; // for testing..

void updateCountReg(uint32_t value)
{
	*bramPtr_countIdx = value; // update count register
	if (ENABLE_PRINT)
	{
		printf("Divide example (%d / PI) = %f  \n", value, (float)(value/M_PI));
	}

}

void MyIsr_0(void *CallbackRef) {


	*((uint32_t *)AXI_IP_TEST_LATENCY_MEASURE) = 1;
    *((uint32_t *)AXI_IP_TEST_LATENCY_MEASURE) = 0;

    if (ENABLE_PRINT)
	{
    		printf("ISR0: Got interrupt! \n");
	}
}

void MyIsr_1(void *CallbackRef) {
	// Add your specific interrupt handling logic here
   //xil_printf("ISR1: Interrupt occurred! \n");
	globalValue += *bramPtr_countIdx  / M_PI;
	if (ENABLE_PRINT)
    {
		printf("ISR1: Got timer interrupt! \n");
    }
}


XIntc InterruptController; // Instance of the Interrupt Controller




int main()
{

	// Current switch value will be stored here
	uint8_t* bramPtr_idx0 = (uint8_t*)XPAR_MICROBLAZE_BRAM_CTRL_S_AXI_BASEADDR; // one byte access
	uint32_t* bramPtr_idx1 = (uint32_t*)(XPAR_MICROBLAZE_BRAM_CTRL_S_AXI_BASEADDR + 4); // 4 byte offset
	uint32_t* bramPtr_idx2 = (uint32_t*)(XPAR_MICROBLAZE_BRAM_CTRL_S_AXI_BASEADDR + 8); // 4 byte offset


	uint8_t tmpVal0 = 0;
    uint32_t tmpVal1 = 0;
    uint32_t tmpVal2 = 0; // 4 byte addressing

    uint32_t writeCount = 0; // 4 byte addressing

    init_platform(); // unsure if this is needed unless we are cacheing???

    int Status;

    // Initialize the AXI Interrupt Controller
    Status = XIntc_Initialize(&InterruptController, XPAR_MBLAZE_AXI_IRQ_CTRL_DEVICE_ID);
    if (Status != XST_SUCCESS) {
        xil_printf("AXI Interrupt Controller initialization failed!\\n\\r");
        return XST_FAILURE;
    }

    // Connect the ISR to the AXI Interrupt Controller - callback
   Status = XIntc_Connect(&InterruptController, XPAR_MBLAZE_AXI_IRQ_CTRL_PICOZED_T_IP_0_ISR_TRIGGER_0_INTR,
						  (XInterruptHandler)MyIsr_0, (void *)0);
   if (Status != XST_SUCCESS) {
	   xil_printf("ISR0: Connecting ISR to Interrupt Controller failed!\\n\\r");
	   return XST_FAILURE;
   }

   Status = XIntc_Connect(&InterruptController, XPAR_MBLAZE_AXI_IRQ_CTRL_PICOZED_T_IP_0_ISR_TRIGGER_1_INTR,
						  (XInterruptHandler)MyIsr_1, (void *)0);
   if (Status != XST_SUCCESS) {
	   xil_printf("ISR1: Connecting ISR to Interrupt Controller failed!\\n\\r");
	   return XST_FAILURE;
   }

   // Start the AXI Interrupt Controller
   Status = XIntc_Start(&InterruptController, XIN_REAL_MODE);
   if (Status != XST_SUCCESS) {
	   xil_printf("Starting Interrupt Controller failed!\\n\\r");
	   return XST_FAILURE;
   }

   // Enable all interrupts
   XIntc_Enable(&InterruptController,
                 XPAR_MBLAZE_AXI_IRQ_CTRL_PICOZED_T_IP_0_ISR_TRIGGER_0_INTR);

   XIntc_Enable(&InterruptController,
                 XPAR_MBLAZE_AXI_IRQ_CTRL_PICOZED_T_IP_0_ISR_TRIGGER_1_INTR);

   // Initialize and enable MicroBlaze exceptions
   Xil_ExceptionInit();
   Xil_ExceptionRegisterHandler(XIL_EXCEPTION_ID_INT,
								(Xil_ExceptionHandler)XIntc_InterruptHandler,
								&InterruptController);
   Xil_ExceptionEnable(); // this will enable interrupts underneath

   // Enable interrupts in your peripheral (e.g., XGpio_InterruptEnable(&Gpio, GPIO_CHANNEL);)

   xil_printf("Done setting up interrupts...\n");


    /** Application Loop **/
	*bramPtr_idx0 = 12; // write some constant value in BRAM

	printf(" ================================================ \n");
	printf(" ================================================ \n");
	printf(" =================WEATHER STREAM================= \n");
	printf(" =========== MICROBLAZE PROJECT START =========== \n");
	printf(" ================================================ \n");
	printf(" ================================================ \n");


	printf("AXI Test: HDL Coder IP Build Date = %u \n",*((uint32_t *)AXI_IP_TEST_BUILD_DATE));

	while(1)
	{

		/* Shared memory access:
		 * This will demonstrate shared memory access between Microblaze and ARM PS using a dual port block ram
		 * Everytime a memory value changes for 0x0, 0x4,0x8, report the value. Then update another register at 0xC
		 */

		if (tmpVal0 != *bramPtr_idx0)
		{
			tmpVal0 = *bramPtr_idx0; // update old value...
			writeCount += 1;
			updateCountReg(writeCount);
		}


		if (tmpVal1 != *bramPtr_idx1)
		{
			tmpVal1 = *bramPtr_idx1;
			writeCount += 1;
			updateCountReg(writeCount);
		}

		if (tmpVal2 != *bramPtr_idx2)
		{
			tmpVal2 = *bramPtr_idx2;
			writeCount += 1;
			updateCountReg(writeCount);
		}

		// 1ms delay
		usleep(10000);
	}

	cleanup_platform();
}
