/******************************************************************************
*
* Copyright (C) 2009 - 2014 Xilinx, Inc.  All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* Use of the Software is limited solely to applications:
* (a) running on a Xilinx device, or
* (b) that interact with a Xilinx device through a bus or interconnect.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* XILINX  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
* OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*
* Except as contained in this notice, the name of the Xilinx shall not be used
* in advertising or otherwise to promote the sale, use or other dealings in
* this Software without prior written authorization from Xilinx.
*
******************************************************************************/

/* AUTOGENERATED COMMENTS
 *
 *
 * This application configures UART 16550 to baud rate 9600.
 * PS7 UART (Zynq) is not initialized by this application, since
 * bootrom/bsp configures it to baud rate 115200
 *
 * ------------------------------------------------
 * | UART TYPE   BAUD RATE                        |
 * ------------------------------------------------
 *   uartns550   9600
 *   uartlite    Configurable only in HW design
 *   ps7_uart    115200 (configured by bootrom/bsp)
 */



/*** Libraries ***/
#include "xparameters.h"	// System related parameters (produced by Vitis based on the provided XSA or HDF)
#include "sleep.h"			// Time based functions
#include "xil_printf.h"
#include <stdio.h>
#include <math.h>

#define AXI_IP_TEST_BASE_ADDR 0x44A00000U
#define AXI_IP_TEST_BUILD_DATE (AXI_IP_TEST_BASE_ADDR+8)

uint32_t* bramPtr_countIdx = (uint32_t*)(XPAR_BRAM_MBLAZE_CTRL_A_S_AXI_BASEADDR + 12); // 4 byte offset

void updateCountReg(uint32_t value)
{
	*bramPtr_countIdx = value; // update count register
	printf("Divide example (%d / PI) = %f  \n", value, (float)(value/M_PI));
}

int main()
{
	/** System Setup **/

	// Current switch value will be stored here
	uint8_t* bramPtr_idx0 = (uint8_t*)XPAR_BRAM_MBLAZE_CTRL_A_S_AXI_BASEADDR; // one byte access
	uint32_t* bramPtr_idx1 = (uint32_t*)(XPAR_BRAM_MBLAZE_CTRL_A_S_AXI_BASEADDR + 4); // 4 byte offset
	uint32_t* bramPtr_idx2 = (uint32_t*)(XPAR_BRAM_MBLAZE_CTRL_A_S_AXI_BASEADDR + 8); // 4 byte offset


	uint8_t tmpVal0 = 0;
    uint32_t tmpVal1 = 0;
    uint32_t tmpVal2 = 0; // 4 byte addressing

    uint32_t writeCount = 0; // 4 byte addressing

    init_platform(); // unsure if this is needed unless we are cacheing???

    /** Application Loop **/
	*bramPtr_idx0 = 12; // write some constant value in BRAM


	printf(" ================================================ \n");
	printf(" ================================================ \n");
	printf(" =================WEATHER STREAM================= \n");
	printf(" =========== MICROBLAZE PROJECT START =========== \n");
	printf(" ================================================ \n");
	printf(" ================================================ \n");


	printf("AXI Test: HDL Coder IP Build Date = %u \n",*((uint32_t *)AXI_IP_TEST_BUILD_DATE));

	while(1)
	{

		/* Shared memory access:
		 * This will demonstrate shared memory access between Microblaze and ARM PS using a dual port block ram
		 * Everytime a memory value changes for 0x0, 0x4,0x8, report the value. Then update another register at 0xC
		 */

		if (tmpVal0 != *bramPtr_idx0)
		{
			printf(" !!!! Value changed  !!!!\n");
			printf("0x%x: New Value = %u \n",bramPtr_idx0,*bramPtr_idx0);
			tmpVal0 = *bramPtr_idx0; // update old value...
			writeCount += 1;
			updateCountReg(writeCount);
		}


		if (tmpVal1 != *bramPtr_idx1)
		{
			printf(" !!!! Value changed  !!!!\n");
			printf("0x%x: New Value = %u \n",bramPtr_idx1, *bramPtr_idx1);
			tmpVal1 = *bramPtr_idx1;
			writeCount += 1;
			updateCountReg(writeCount);
		}

		if (tmpVal2 != *bramPtr_idx2)
		{
			printf(" !!!! Value changed  !!!!\n");
			printf("0x%x: New Value = %u \n",bramPtr_idx2, *bramPtr_idx2);
			tmpVal2 = *bramPtr_idx2;
			writeCount += 1;
			updateCountReg(writeCount);
		}

		// 1ms delay
		usleep(10000);
	}

	cleanup_platform();
}
