-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/test_ip/picozed_t_ip_src_Detect_Increase1.vhd
-- Created: 2025-10-08 11:52:52
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: picozed_t_ip_src_Detect_Increase1
-- Source Path: test_ip/picozed_test_ip/MeasureLatency/Detect Increase1
-- Hierarchy Level: 2
-- Model version: 1.78
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY picozed_t_ip_src_Detect_Increase1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        U                                 :   IN    std_logic;
        Y                                 :   OUT   std_logic
        );
END picozed_t_ip_src_Detect_Increase1;


ARCHITECTURE rtl OF picozed_t_ip_src_Detect_Increase1 IS

  -- Signals
  SIGNAL U_k_1                            : std_logic;
  SIGNAL FixPt_Relational_Operator_out1   : std_logic;

BEGIN
  -- Edge
  -- U(k)

  -- 
  -- Store in Global RAM
  Delay_Input1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        U_k_1 <= '0';
      ELSIF enb = '1' THEN
        U_k_1 <= U;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;


  
  FixPt_Relational_Operator_out1 <= '1' WHEN U > U_k_1 ELSE
      '0';

  Y <= FixPt_Relational_Operator_out1;

END rtl;

